function tableout = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   DuckBunny2Fall2015Eating = importfile('DuckBunny2_Fall2015_Eating.xlsx','Sheet1',2,1972);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/05/26 20:03:52

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 1972;
end

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread(workbookFile, sheetName, sprintf('A%d:W%d',startRow(1),endRow(1)),'' , @convertSpreadsheetExcelDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:W%d',startRow(block),endRow(block)),'' , @convertSpreadsheetExcelDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dates = [dates;tmpDateNumBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,8,12,13,16,20]);
raw = raw(:,[2,3,5,6,7,9,10,11,14,15,17,18,19,21,22,23]);
dates = dates(:,4);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),dates); % Find non-numeric cells
dates(R) = {NaN}; % Replace non-numeric Excel dates with NaN

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.stud_id = cellVectors(:,1);
tableout.gender = data(:,1);
tableout.age = data(:,2);
dates(~cellfun(@(x) isnumeric(x) || islogical(x), dates)) = {NaN};
tableout.birth = datetime([dates{:,1}].', 'ConvertFrom', 'Excel', 'Format', 'dd/MM/yyyy');
tableout.inches = data(:,3);
tableout.cm = data(:,4);
tableout.pounds = data(:,5);
tableout.kg = cellVectors(:,2);
tableout.edu = data(:,6);
tableout.ethnic = data(:,7);
tableout.english = data(:,8);
tableout.eng_other = cellVectors(:,3);
tableout.eng_lang_other = cellVectors(:,4);
tableout.lang_after_english = data(:,9);
tableout.colour = data(:,10);
tableout.colour_other = cellVectors(:,5);
tableout.mobility = data(:,11);
tableout.glasses = data(:,12);
tableout.q1a = data(:,13);
tableout.q2a = cellVectors(:,6);
tableout.q2b = data(:,14);
tableout.q2c = data(:,15);
tableout.q3a = data(:,16);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% tableout.birth=datenum(tableout.birth);

